### PR TITLE
Support more jekyll versions

### PR DESCRIPTION
**Pull request by fosberyi**
* All tests back to green
* Added the [apprasal gem](https://github.com/thoughtbot/appraisal) to manage multiple version testing
* Double-dipping on `strip_html` and `condense` filters - Jekyll 3.1 seems to be adding some extra html encoding on build now.
* Now having some encoding issues in Jekyll 2.0

### CODE REVIEW

**Comment by fosberyi** [comment]
Follow up on the encoding issues - it's also happening in the current master branch. It's just a printable ASCII character problem, but it's not the end of the world. EG: `Youâ€™ll` rather than `You'll`.

 So, everything is back to normal after adding moving 3.0-prebeta -> 3.0 stable and adding 3.1. I think this is a good starting point for moving from the monkeypatching to the proper Jekyll plugin structure from >=3.0.

**Comment by fosberyi** [comment]
Hey @afeld, just wondering if you've had a chance to look at this? Maybe my fault, I should have pinged you off the bat.

Thanks!

**Comment by tute** [comment]
This looks good to me. Would you please squash your commits together, with a nice commit message (like your PR description)? Thank you!

**Comment by fosberyi** [comment]
Sure thing - all squashed up!

**Comment by afeld** [comment]
I am so so sorry for not getting to this sooner...this is AWESOME. Thanks so much!

**Comment by fosberyi** [comment]
@afeld No worries, man. I heard you've been working like crazy, which unfortunately, I totally understand;)

Thanks for merging - on to the monkeypatching!

**Comment by afeld** [comment]
🐒 🐒 🐒

**Pull request merged**
